name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  tests_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install

      - name: Check coding standards
        run: composer cs-check

      - name: Check static analysis (PHPStan)
        run: composer stan

      - name: Run tests
        run: composer test

      - name: Check markdown files
        run: composer md-check

      - name: Save test output
        run: |
          mkdir -p tests/_output/
          cp -r tests/_output/coverage public/
        if: always()

      - name: Upload test output artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-output
          path: public

  deploy_to_pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Move coverage to public directory
        run: mv tests/_output/coverage public/

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public